# Generated by Django 2.0.5 on 2018-05-11 14:37

import captive_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoveWiFiQRScheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WiFiQR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expiration_time', models.DateTimeField()),
                ('qr_code', models.FileField(upload_to=captive_portal.models.upload_directory)),
                ('current_connected', models.IntegerField(default=0)),
                ('max_connected', models.IntegerField(default=0)),
            ],
        ),
    ]
