# Generated by Django 2.0.4 on 2018-05-01 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('expiration_time', models.DateTimeField(verbose_name=datetime.datetime(2018, 5, 1, 13, 53, 43, 221506))),
            ],
        ),
    ]
