# Generated by Django 2.0.4 on 2018-05-01 04:18

import captive_portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captive_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wifiuser',
            name='qr_code',
            field=models.FileField(default='758580.png'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wifiuser',
            name='expiration_time',
            field=models.DateTimeField(),
        ),
    ]
